export const MOCK_PRODUCTS = [
  // ── Smart Watches ────────────────────────────────────────────
  {
    id: 'mock-sw-1',
    name: 'Apple Watch Series 9 (GPS, 41mm)',
    brand: 'Apple',
    category: 'smartwatch',
    price: 41900,
    amazon_rating: 4.7,
    image_url: 'https://m.media-amazon.com/images/I/71pRLsEhOUL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Health Monitoring', 'Fitness Tracking', 'Notifications'],
      priority: 'Health Sensors',
      compatibility: 'iPhone',
    },
    specs: {
      display: '1.9" Always-On Retina LTPO OLED',
      battery: '18 hours',
      health_sensors: 'ECG, Blood Oxygen, Heart Rate, Crash Detection',
      connectivity: 'Bluetooth 5.3, WiFi, UWB',
      compatibility: 'iPhone only',
      water_resistance: '50 metres',
    },
  },
  {
    id: 'mock-sw-2',
    name: 'Samsung Galaxy Watch 6 (44mm)',
    brand: 'Samsung',
    category: 'smartwatch',
    price: 28999,
    amazon_rating: 4.4,
    image_url: 'https://m.media-amazon.com/images/I/71KFqJt+lJL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Health Monitoring', 'Fitness Tracking'],
      priority: 'Health Sensors',
      compatibility: 'Android',
    },
    specs: {
      display: '1.5" Super AMOLED',
      battery: '40 hours',
      health_sensors: 'BioActive Sensor, ECG, Blood Pressure',
      connectivity: 'Bluetooth 5.3, WiFi, NFC',
      compatibility: 'Android',
      water_resistance: '5 ATM + IP68',
    },
  },
  {
    id: 'mock-sw-3',
    name: 'Garmin Forerunner 255',
    brand: 'Garmin',
    category: 'smartwatch',
    price: 31990,
    amazon_rating: 4.5,
    image_url: 'https://m.media-amazon.com/images/I/51DWVczFeSL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Fitness Tracking'],
      priority: 'GPS & Sports',
      compatibility: 'Any',
    },
    specs: {
      display: '1.3" MIP Display',
      battery: '14 days',
      health_sensors: 'Heart Rate, SpO2, Stress, HRV',
      connectivity: 'Bluetooth, ANT+, GPS',
      compatibility: 'iOS & Android',
      water_resistance: '5 ATM',
    },
  },
  {
    id: 'mock-sw-4',
    name: 'Noise ColorFit Pro 5',
    brand: 'Noise',
    category: 'smartwatch',
    price: 3999,
    amazon_rating: 4.1,
    image_url: 'https://m.media-amazon.com/images/I/61IovqcltnL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Fitness Tracking', 'Notifications', 'Style'],
      priority: 'Battery Life',
      compatibility: 'Any',
    },
    specs: {
      display: '1.85" AMOLED',
      battery: '7 days',
      health_sensors: 'Heart Rate, SpO2, Stress',
      connectivity: 'Bluetooth 5.3',
      compatibility: 'iOS & Android',
      water_resistance: 'IP68',
    },
  },
  // ── Mobile Phones ─────────────────────────────────────────────
  {
    id: 'mock-mob-1',
    name: 'Samsung Galaxy S24 (8GB/256GB)',
    brand: 'Samsung',
    category: 'mobile',
    price: 74999,
    amazon_rating: 4.5,
    image_url: 'https://m.media-amazon.com/images/I/71NS2RsGFFL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Photography', 'Business', 'Everyday Use'],
      priority: 'Performance',
      storage: '256GB',
    },
    specs: {
      processor: 'Snapdragon 8 Gen 3',
      ram: '8GB',
      storage: '256GB',
      camera: '50MP + 12MP + 10MP',
      battery: '4000mAh, 25W fast charge',
      display: '6.2" Dynamic AMOLED 2X, 120Hz',
      os: 'Android 14 (One UI 6.1)',
    },
  },
  {
    id: 'mock-mob-2',
    name: 'OnePlus 12R (16GB/256GB)',
    brand: 'OnePlus',
    category: 'mobile',
    price: 39999,
    amazon_rating: 4.4,
    image_url: 'https://m.media-amazon.com/images/I/61xqpIioJeL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Gaming', 'Everyday Use'],
      priority: 'Performance',
      storage: '256GB',
    },
    specs: {
      processor: 'Snapdragon 8 Gen 2',
      ram: '16GB',
      storage: '256GB',
      camera: '50MP + 8MP + 2MP',
      battery: '5500mAh, 100W SuperVOOC',
      display: '6.78" AMOLED, 120Hz ProXDR',
      os: 'Android 14 (OxygenOS 14)',
    },
  },
  {
    id: 'mock-mob-3',
    name: 'Poco X6 Pro (12GB/256GB)',
    brand: 'Poco',
    category: 'mobile',
    price: 26999,
    amazon_rating: 4.3,
    image_url: 'https://m.media-amazon.com/images/I/61Wfb8QFQKL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Gaming', 'Everyday Use'],
      priority: 'Performance',
      storage: '256GB',
    },
    specs: {
      processor: 'Dimensity 8300-Ultra',
      ram: '12GB',
      storage: '256GB',
      camera: '64MP + 8MP + 2MP',
      battery: '5000mAh, 67W Turbo Charge',
      display: '6.67" AMOLED, 144Hz',
      os: 'Android 14 (MIUI 14)',
    },
  },
  {
    id: 'mock-mob-4',
    name: 'Redmi Note 13 Pro+ (8GB/256GB)',
    brand: 'Redmi',
    category: 'mobile',
    price: 29999,
    amazon_rating: 4.4,
    image_url: 'https://m.media-amazon.com/images/I/61y8lf9VMTL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Photography', 'Everyday Use'],
      priority: 'Camera',
      storage: '256GB',
    },
    specs: {
      processor: 'Dimensity 7200-Ultra',
      ram: '8GB',
      storage: '256GB',
      camera: '200MP + 8MP + 2MP',
      battery: '5000mAh, 120W HyperCharge',
      display: '6.67" AMOLED, 120Hz',
      os: 'Android 13 (MIUI 14)',
    },
  },
  // ── Laptops ───────────────────────────────────────────────────
  {
    id: 'mock-1',
    name: 'ASUS ROG Strix G15',
    brand: 'ASUS',
    category: 'laptop',
    price: 75000,
    amazon_rating: 4.4,
    image_url: 'https://m.media-amazon.com/images/I/81eDVLJGZGL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Gaming'],
      priority: 'Maximum Performance',
      battery: 'Not Important',
    },
    specs: {
      processor: 'AMD Ryzen 7 6800H',
      ram: '16GB DDR5',
      storage: '512GB NVMe SSD',
      display: '15.6" 144Hz FHD IPS',
      battery: '90Wh (4-5 hours)',
      weight: '2.3 kg',
      os: 'Windows 11 Home',
      graphics: 'NVIDIA RTX 3060 6GB',
    },
  },
  {
    id: 'mock-2',
    name: 'Dell XPS 15 9530',
    brand: 'Dell',
    category: 'laptop',
    price: 145000,
    amazon_rating: 4.6,
    image_url: 'https://m.media-amazon.com/images/I/71dXKEHRFQL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Video Editing & Design', 'Office & Work'],
      priority: 'Balanced',
      battery: 'Somewhat',
    },
    specs: {
      processor: 'Intel Core i7-13700H',
      ram: '16GB DDR5',
      storage: '512GB NVMe SSD',
      display: '15.6" OLED 3.5K Touch',
      battery: '86Wh (6-8 hours)',
      weight: '1.86 kg',
      os: 'Windows 11 Pro',
      graphics: 'NVIDIA RTX 4060 8GB',
    },
  },
  {
    id: 'mock-3',
    name: 'Acer Aspire 5 A515',
    brand: 'Acer',
    category: 'laptop',
    price: 42000,
    amazon_rating: 4.2,
    image_url: 'https://m.media-amazon.com/images/I/71UiST5VAQL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['College & Study', 'Office & Work'],
      priority: 'Balanced',
      battery: 'Very Important',
    },
    specs: {
      processor: 'Intel Core i5-1235U',
      ram: '8GB DDR4',
      storage: '512GB SSD',
      display: '15.6" FHD IPS',
      battery: '57Wh (7-8 hours)',
      weight: '1.8 kg',
      os: 'Windows 11 Home',
      graphics: 'Intel Iris Xe',
    },
  },
  {
    id: 'mock-4',
    name: 'HP Pavilion 15-eg3081TU',
    brand: 'HP',
    category: 'laptop',
    price: 58000,
    amazon_rating: 4.3,
    image_url: 'https://m.media-amazon.com/images/I/61p3vHtGYuL._SX522_.jpg',
    affiliate_link: 'https://amazon.in',
    is_active: true,
    tags: {
      use_case: ['Office & Work', 'College & Study'],
      priority: 'Lightweight & Portable',
      battery: 'Somewhat',
    },
    specs: {
      processor: 'Intel Core i5-1335U',
      ram: '16GB DDR4',
      storage: '512GB SSD',
      display: '15.6" FHD IPS Anti-Glare',
      battery: '43Wh (5-6 hours)',
      weight: '1.75 kg',
      os: 'Windows 11 Home',
      graphics: 'Intel Iris Xe',
    },
  },
]
